### PR TITLE
Description added for all apis

### PR DESCRIPTION
**Pull request by neha0305verma**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @neha0305verma,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://682.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://682.qa.docs.sunbird.org/api-documentation/apis/coursebatchmanapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseenrolmentapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseprogressapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/tocapi// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @neha0305verma,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://682.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://682.qa.docs.sunbird.org/api-documentation/apis/coursebatchmanapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseenrolmentapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseprogressapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/tocapi// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @neha0305verma,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://682.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://682.qa.docs.sunbird.org/api-documentation/apis/coursebatchmanapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseenrolmentapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseprogressapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/tocapi// <br />  <br/> **Modified sections are -** <br />

**Review by PradyumnaNagendra — APPROVED** [review]

**Comment by keshavprasadms** [comment]
Hello @neha0305verma,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://682.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://682.qa.docs.sunbird.org/api-documentation/apis/coursebatchmanapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseenrolmentapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/courseprogressapi// <br /> - http://682.qa.docs.sunbird.org/api-documentation/apis/tocapi// <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
