### PR TITLE
1.10

### PR DESCRIPTION
**Pull request by mathewjpallan**
This PR has updates to the server installation documentation to make it more accurate and user friendly.

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @mathewjpallan,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://329.qa.docs.sunbird.org/1.10/ .<br/> **Note:** Only _1.10_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/configuring_installer/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation// <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/prerequisites/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/running_the_installer/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @mathewjpallan,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://329.qa.docs.sunbird.org/1.10/ .<br/> **Note:** Only _1.10_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/configuring_installer/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation// <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/prerequisites/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/running_the_installer/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @mathewjpallan,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://329.qa.docs.sunbird.org/1.10/ .<br/> **Note:** Only _1.10_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/configuring_installer/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation// <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/prerequisites/ <br /> - http://329.qa.docs.sunbird.org/1.10/developer-docs/server-installation/running_the_installer/ <br />  <br/> **Modified sections are -** <br />

**Comment by Basreena** [comment]
The document has been verified by Mathew.

Configuration parameters are not in alphabetical order but are arranged as they appear in the config file.

**Pull request merged**
