### PR TITLE
Updated release-3.4.0 sunbird installation steps

### PR DESCRIPTION
**Pull request by G33tha**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://651.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/adminutil_refresh_token/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/core-services/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/data-pipeline/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/keycloak_lms_configuration/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://651.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/adminutil_refresh_token/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/core-services/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/data-pipeline/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/keycloak_lms_configuration/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://651.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/adminutil_refresh_token/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/core-services/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/data-pipeline/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/keycloak_lms_configuration/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by G33tha** [comment]
@keshavprasadms Please review PR

**Comment by keshavprasadms** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://651.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/adminutil_refresh_token/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/ansible-variables/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/core-services/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/data-pipeline/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/keycloak_lms_configuration/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/load_balancer_setup/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/plugins/ <br /> - http://651.qa.docs.sunbird.org/3.5.0/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Pull request closed without merging**
