### PR TITLE
document for QuML bulk upload as part of JIRA key-> SB-25750 

### PR DESCRIPTION
**Pull request by Hari-1027**
document for QuML bulk upload as part of JIRA key-> SB-25750

### CODE REVIEW

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by mohitga** [comment]
@Hari-1027  there is a conflict in the PR. This need to be resolved. look into this urgently.

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @Hari-1027,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://845.qa.docs.sunbird.org/4.2.0/ .<br/> **Note:** Only _4.2.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://845.qa.docs.sunbird.org/4.2.0/apis/questionapi// <br />  <br/> **Modified sections are -** <br />

**Comment by Hari-1027** [comment]
@mohitga Have resolve all the conflicts and corrected the errors. Verified the result links of the document.

**Pull request closed without merging**
