### PR TITLE
feat(uci): added the UCI documentation

### PR DESCRIPTION
**Pull request by Shruti3004**
Added the UCI openapi documnetation.

### CODE REVIEW

**Comment by amorphous-1** [comment]
Hello @Shruti3004,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://853.qa.docs.sunbird.org/4.3.0/ .<br/> **Note:** Only _4.3.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://853.qa.docs.sunbird.org/4.3.0/apis/uciapi// <br /> - http://853.qa.docs.sunbird.org/4.3.0/apis/uciapi// <br />  <br/> **Modified sections are -** <br />

**Comment by mohitga** [comment]
@Shruti3004 please add context to the API documentation.

**Comment by Shruti3004** [comment]
> @Shruti3004 are you done with the changes and planning to merge with the 4.3.0 release?

Hi Mohit actually one from our team going to contact you, precisely I wanted to understand what's actually the context to the API documentation, like a description to the APIs?

**Comment by mohitga** [comment]
@Shruti3004  are you planning to deploy these APIs in the 4.3 release. 
yes, the context is the description of the APIs. What is the objective of these APIs where and how to use them? 
This is done to ensure APIs created by any partner is easy to understand and use by other partners as well.

**Comment by mohitga** [comment]
@aayushkedia95 Can you please move the PR and raise the merge request with 4.5 branch?

**Comment by Sunitashelar** [comment]
Closing this PR without merging it.

**Pull request closed without merging**
