### PR TITLE
issue #SB-15599 feat: changes for adding license attribute during cre…

### PR DESCRIPTION
**Pull request by manzarul**
…ate or update rootOrg.

Note: This PR need to be merged with release-2.6.0 only. As of now i can find latest branch is 2.4.0 , so i raised PR for this branch , but before merged some one need to update beanch to 2.6.0

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://524.qa.docs.sunbird.org/2.4.0/ .<br/> **Note:** Only _2.4.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://524.qa.docs.sunbird.org/2.4.0/apis/orgapi// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://524.qa.docs.sunbird.org/2.4.0/ .<br/> **Note:** Only _2.4.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://524.qa.docs.sunbird.org/2.4.0/apis/orgapi// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://524.qa.docs.sunbird.org/2.4.0/ .<br/> **Note:** Only _2.4.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://524.qa.docs.sunbird.org/2.4.0/apis/orgapi// <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
@manzarul there are 3 conflicts between this file and the older file, when i change the brannch. Could you please resolve them and send the PR again to the newly created 2.6 branch?

**Comment by manzarul** [comment]
@Sunitashelar conflict is resolved now.

**Comment by keshavprasadms** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://524.qa.docs.sunbird.org/2.6.0/ .<br/> **Note:** Only _2.6.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://524.qa.docs.sunbird.org/2.6.0/apis/orgapi// <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
