### PR TITLE
Issue #SB-22862 feat: Collection CSV Hierarchy feature API documentation

### PR DESCRIPTION
**Pull request by Jayaprakash8887**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @Jayaprakash8887,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://778.qa.docs.sunbird.org/4.0.0/ .<br/> **Note:** Only _4.0.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br /> - http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @Jayaprakash8887,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://778.qa.docs.sunbird.org/4.0.0/ .<br/> **Note:** Only _4.0.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br /> - http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
@maheshkumargangula please review the documentation before it is merged.

**Comment by keshavprasadms** [comment]
Hello @Jayaprakash8887,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://778.qa.docs.sunbird.org/4.0.0/ .<br/> **Note:** Only _4.0.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br /> - http://778.qa.docs.sunbird.org/4.0.0/apis/collectioncsvapi// <br />  <br/> **Modified sections are -** <br />

**Pull request closed without merging**
