### PR TITLE
Changes for unenroll api end point and request body

### PR DESCRIPTION
**Pull request by manzarul**
Changes for unenroll api end point and request body

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://392.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://392.qa.docs.sunbird.org/master/apis/coursebatchmanapi// <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://392.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://392.qa.docs.sunbird.org/master/apis/coursebatchmanapi// <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://392.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://392.qa.docs.sunbird.org/master/apis/coursebatchmanapi// <br /> - http://392.qa.docs.sunbird.org/master/developer-docs/configuring_sunbird/course_framework_id/ <br />  <br/> **Modified sections are -** <br />

**Comment by manzarul** [comment]
sending two different PR.

**Pull request closed without merging**
