### PR TITLE
release 3.6.0 documents

### PR DESCRIPTION
**Pull request by badaltechiepi**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @badaltechiepi,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://730.qa.docs.sunbird.org/3.6.0/ .<br/> **Note:** Only _3.6.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/ansible-variables/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/core-services/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/data-pipeline/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/post_installation_configuration/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/understanding-jenkins-scripts-jobs-parameters-and-variables/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/upgrade/build_n_deploy/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/upgrade// <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/upgrade/jenkins_updates/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/upgrade/update_ansible_variables/ <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @badaltechiepi,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://730.qa.docs.sunbird.org/3.6.0/ .<br/> **Note:** Only _3.6.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://730.qa.docs.sunbird.org/3.6.0/apis// <br /> - http://730.qa.docs.sunbird.org/3.6.0/apis// <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/core-services/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/data-pipeline/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/post_installation_configuration/ <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @badaltechiepi,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://730.qa.docs.sunbird.org/3.6.0/ .<br/> **Note:** Only _3.6.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://730.qa.docs.sunbird.org/3.6.0/apis// <br /> - http://730.qa.docs.sunbird.org/3.6.0/apis// <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/core-services/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/data-pipeline/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/jenkins-setup/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/knowledge-platform/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/plugins/ <br /> - http://730.qa.docs.sunbird.org/3.6.0/developer-docs/server-installation/post_installation_configuration/ <br />  <br/> **Modified sections are -** <br />

**Comment by badaltechiepi** [comment]
@Sunitashelar Post merged the PR, the changes are not getting reflected in the Documentation section. Kindly check.

**Pull request merged**
