### PR TITLE
Enabling Pre checks for the APIs to follow merging standards

### PR DESCRIPTION
**Pull request by SMYALTAMASH**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @SMYALTAMASH,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://738.qa.docs.sunbird.org/3.8.0/ .<br/> **Note:** Only _3.8.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by SMYALTAMASH** [comment]
PASSING AND FAILED CIRCLECI REPORT: 
https://app.circleci.com/pipelines/github/project-sunbird/sunbird.org-docs/695/workflows/d827884c-3017-4de8-8239-67e95cbc40a0/jobs/3192
https://app.circleci.com/pipelines/github/project-sunbird/sunbird.org-docs/695/workflows/d827884c-3017-4de8-8239-67e95cbc40a0/jobs/3193

**Pull request merged**
