### PR TITLE
release-4.1.0 upgrade doc changes

### PR DESCRIPTION
**Pull request by G33tha**

### CODE REVIEW

**Comment by amorphous-1** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://828.qa.docs.sunbird.org/4.1.0/ .<br/> **Note:** Only _4.1.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://828.qa.docs.sunbird.org/4.1.0/developer-docs/upgrade// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://828.qa.docs.sunbird.org/4.1.0/ .<br/> **Note:** Only _4.1.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://828.qa.docs.sunbird.org/4.1.0/developer-docs/upgrade// <br />  <br/> **Modified sections are -** <br />

**Comment by G33tha** [comment]
@Sunitashelar please merge this PR

**Comment by amorphous-1** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://828.qa.docs.sunbird.org/4.1.0/ .<br/> **Note:** Only _4.1.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://828.qa.docs.sunbird.org/4.1.0/developer-docs/upgrade// <br />  <br/> **Modified sections are -** <br />

**Comment by amorphous-1** [comment]
Hello @G33tha,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://828.qa.docs.sunbird.org/4.1.0/ .<br/> **Note:** Only _4.1.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://828.qa.docs.sunbird.org/4.1.0/developer-docs/upgrade// <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
