### PR TITLE
Issue #SB-21326 fix: Discussion forum micro services

### PR DESCRIPTION
**Pull request by VenkatKadiveti**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://676.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://676.qa.docs.sunbird.org/3.5.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://676.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://676.qa.docs.sunbird.org/3.5.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://676.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://676.qa.docs.sunbird.org/3.5.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://676.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://676.qa.docs.sunbird.org/3.5.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://676.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://676.qa.docs.sunbird.org/3.5.0/apis/feedapi// <br />  <br/> **Modified sections are -** <br />

**Comment by VenkatKadiveti** [comment]
Created new PR

**Pull request closed without merging**
