### PR TITLE
Temp PR

### PR DESCRIPTION
**Pull request by PradyumnaNagendra**

### CODE REVIEW

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by keshavprasadms** [comment]
Hello @PradyumnaNagendra,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://646.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br /> - http://646.qa.docs.sunbird.org/api-documentation/apis/credentials// <br />  <br/> **Modified sections are -** <br />

**Comment by Basreena** [comment]
@PradyumnaNagendra , the qa links aren't loading. Am unsure what the error could be, request you to check this, please. Thanks.

cc: @Sunitashelar

**Pull request closed without merging**
