### PR TITLE
Issue #SB-9139 feat: Document - How to generate JWT

### PR DESCRIPTION
**Pull request by ahghatol**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @ahghatol,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://371.qa.docs.sunbird.org/1.9/ .<br/> **Note:** Only _1.9_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://371.qa.docs.sunbird.org/1.9/developer-docs/telemetry/authtokengenerator_jslibrary/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @ahghatol,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://371.qa.docs.sunbird.org/1.9/ .<br/> **Note:** Only _1.9_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://371.qa.docs.sunbird.org/1.9/developer-docs/telemetry/authtokengenerator_jslibrary/ <br />  <br/> **Modified sections are -** <br />

**Comment by ahghatol** [comment]
@kochhar No, This document is only for how to get auth credentials from Ekstep portal and generate a JWT using it. 

However, I think we can have a separate page for jwt generation document and we can link it from both the docs 
- How to get auth credentials from Ekstep portal and
- Generate JWT for the consumer on own Sunbird server installation

**Comment by lakhanmandloi** [comment]
Hello @ahghatol,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://371.qa.docs.sunbird.org/1.9/ .<br/> **Note:** Only _1.9_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://371.qa.docs.sunbird.org/1.9/developer-docs/telemetry/authtokengenerator_jslibrary/ <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
closing PR without merging

**Pull request closed without merging**
