### PR TITLE
updated server install docs

### PR DESCRIPTION
**Pull request by NupurSancheti**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/additional_info/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/additional_info/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/additional_info/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/additional_info/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @NupurSancheti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://207.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/additional_info/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/configuring_installer/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/ekstep_keys/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation// <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/installation/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/overview/ <br /> - http://207.qa.docs.sunbird.org/master/developer-docs/server-installation/prerequisites/ <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Reviewed all pages for front matter and incorporation of review comments received. Clarifications sought on the following pages: 
1) Installation 2) Prerequisites 3) Configuring installer

**Pull request merged**
