### PR TITLE
Config service variable list

### PR DESCRIPTION
**Pull request by Basreena**

### CODE REVIEW

**Comment by Basreena** [comment]
@Sunita, please note this page is incomplete. I have created the page with the information available in the Sunbird Variable Tracker. Will assign Bajaj to furnish/fill the empty columns.

This page corresponds to jira ticket SB:3303

**Comment by lakhanmandloi** [comment]
Hello @Basreena,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://297.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://297.qa.docs.sunbird.org/master/developer-docs/configuring_sunbird/env_variables_config/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @Basreena,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://297.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://297.qa.docs.sunbird.org/master/developer-docs/configuring_sunbird/env_variables_config/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @Basreena,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://297.qa.docs.sunbird.org/master/ .<br/> **Note:** Only _master_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://297.qa.docs.sunbird.org/master/developer-docs/configuring_sunbird/env_variables_config/ <br /> - http://297.qa.docs.sunbird.org/master/release_notes// <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
